[package]
name = "lepo"
edition = "2024"
version = "0.0.1"

[dependencies]
anyhow = "1.0.99"
async-trait = "0.1.89"
axum-macros = "0.5.0"
cargo-watch = "8.5.3"
clap_builder = "4.5.47"
dotenvy = "0.15.7"
gemini_client_rs = "0.6.0"
headers = "0.4.1"
json = "0.12.4"
serde_json = "1.0.143"
thiserror = "2.0.16"
tower = "0.5.2"
tracing = "0.1.41"
uuid = "1.18.1"

[dependencies.axum]
version = "0.8.4"
features = ["multipart", "macros"]

[dependencies.axum-extra]
version = "0.10.1"
features = ["typed-header"]

[dependencies.clap]
version = "4.5.47"
features = ["derive", "env"]

[dependencies.langchain-rust]
version = "4.6.0"
features = ["postgres"]

[dependencies.reqwest]
version = "0.12.23"
features = ["blocking", "rustls-tls-webpki-roots"]
default-features = false

[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[dependencies.sqlx]
version = "0.8.6"
features = ["runtime-tokio", "postgres"]

[dependencies.tokio]
version = "1.47.1"
features = ["full"]

[dependencies.tower-http]
version = "0.6.6"
features = ["trace"]

[dependencies.tracing-subscriber]
version = "0.3.20"
features = ["fmt"]

[lib]
path = "src/lib.rs"
name = "lepo"
plugin = false
proc-macro = false
edition = "2024"
required-features = []
crate-type = ["lib"]
